name: build and quality

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
    snyk_token: ${{ secrets.SNYK_TOKEN }}

jobs:
  quality-check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Check quality
        run: |
          npm ci --force
          git submodule update --init --recursive --remote
          bash .github/workflows/scripts/quality.sh
